const tagListArray = [
  "webdevelopment",
  "webdesign",
  "webdeveloper",
  "html",
  "website",
  "coding",
  "programming",
  "css",
  "javascript",
  "digitalmarketing",
  "developer",
  "seo",
  "websitedesign",
  "programmer",
  "webdesigner",
  "marketing",
  "web",
  "code",
  "python",
  "design",
  "coder",
  "java",
  "software",
  "wordpress",
  "ecommerce",
  "php",
  "softwaredeveloper",
  "programming bootcamp",
  "technology",
  "development",
];

export default tagListArray;
